// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxawMLEHPgDY4SAMPvCYw5pLFqCYqIdRA',
    appId: '1:158730534029:web:eaf700638ddafa336436c4',
    messagingSenderId: '158730534029',
    projectId: 'barbearia-estilo-c19cf',
    authDomain: 'barbearia-estilo-c19cf.firebaseapp.com',
    storageBucket: 'barbearia-estilo-c19cf.firebasestorage.app',
    measurementId: 'G-B4GVGEHWJS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCL5PGtD58A58mI5qLtWXK1DtLLh2nW6UQ',
    appId: '1:158730534029:android:9c33e22cd84405bb6436c4',
    messagingSenderId: '158730534029',
    projectId: 'barbearia-estilo-c19cf',
    storageBucket: 'barbearia-estilo-c19cf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuQSzJ5BB-OkwBF6cnbGBtmvRhK0ttBYM',
    appId: '1:158730534029:ios:1e4ced10280ea2086436c4',
    messagingSenderId: '158730534029',
    projectId: 'barbearia-estilo-c19cf',
    storageBucket: 'barbearia-estilo-c19cf.firebasestorage.app',
    iosBundleId: 'com.example.barbeariaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuQSzJ5BB-OkwBF6cnbGBtmvRhK0ttBYM',
    appId: '1:158730534029:ios:1e4ced10280ea2086436c4',
    messagingSenderId: '158730534029',
    projectId: 'barbearia-estilo-c19cf',
    storageBucket: 'barbearia-estilo-c19cf.firebasestorage.app',
    iosBundleId: 'com.example.barbeariaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxawMLEHPgDY4SAMPvCYw5pLFqCYqIdRA',
    appId: '1:158730534029:web:cad1b57ba9cf107d6436c4',
    messagingSenderId: '158730534029',
    projectId: 'barbearia-estilo-c19cf',
    authDomain: 'barbearia-estilo-c19cf.firebaseapp.com',
    storageBucket: 'barbearia-estilo-c19cf.firebasestorage.app',
    measurementId: 'G-GPHSVEG6QC',
  );
}
